# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x07\n\x05\x45mpty\"_\n\x0cInferRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x13\n\x0binstruction\x18\x02 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\x03\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\"\x84\x01\n\rInferResponse\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x03\x12\x11\n\twaypoints\x18\x02 \x03(\x02\x12\x13\n\x0bn_waypoints\x18\x03 \x01(\x05\x12\x19\n\x11inference_time_ms\x18\x04 \x01(\x02\x12\r\n\x05\x65rror\x18\x05 \x01(\t\x12\x0f\n\x07success\x18\x06 \x01(\x08\"G\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x14\n\x0cmodel_status\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t2\xd0\x01\n\x10InferenceService\x12:\n\x05Infer\x12\x17.inference.InferRequest\x1a\x18.inference.InferResponse\x12\x44\n\x0bStreamInfer\x12\x17.inference.InferRequest\x1a\x18.inference.InferResponse(\x01\x30\x01\x12:\n\x0bHealthCheck\x12\x10.inference.Empty\x1a\x19.inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_INFERREQUEST']._serialized_start=39
  _globals['_INFERREQUEST']._serialized_end=134
  _globals['_INFERRESPONSE']._serialized_start=137
  _globals['_INFERRESPONSE']._serialized_end=269
  _globals['_HEALTHRESPONSE']._serialized_start=271
  _globals['_HEALTHRESPONSE']._serialized_end=342
  _globals['_INFERENCESERVICE']._serialized_start=345
  _globals['_INFERENCESERVICE']._serialized_end=553
# @@protoc_insertion_point(module_scope)

